-- Create Users Table
create table users (
  id uuid references auth.users not null primary key,
  register_number text unique,
  full_name text not null,
  role text check (role in ('student', 'warden')) not null,
  hostel_block text,
  room_number text,
  parent_mobile text,
  profile_pic_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Leave Requests Table
create table leave_requests (
  id bigint generated by default as identity primary key,
  student_id uuid references users(id) not null,
  type text check (type in ('Outing', 'Leave')) not null,
  reason text not null,
  out_date timestamp with time zone not null,
  in_date timestamp with time zone not null,
  status text check (status in ('Approved', 'Pending', 'Rejected')) default 'Pending',
  document_url text,
  actual_out_time timestamp with time zone,
  actual_in_time timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table users enable row level security;
alter table leave_requests enable row level security;

-- Policies (MVP: Allow All for simplicity, or slightly restricted)
-- Allow read access to everyone for now (simulating polished MVP where we trust the app logic)
create policy "Public users are viewable by everyone" on users for select using (true);
create policy "Users can insert their own profile" on users for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on users for update using (auth.uid() = id);

-- Leave Requests Policies
create policy "See all leave requests" on leave_requests for select using (true);
create policy "Create leave requests" on leave_requests for insert with check (auth.uid() = student_id);
create policy "Update leave requests" on leave_requests for update using (true); -- Wardens need to update status, Students update actual times

-- Storage Bucket Policies (If creating via SQL is supported, though usually done in UI)
-- insert into storage.buckets (id, name, public) values ('leave_docs', 'leave_docs', true);
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'leave_docs' );
-- create policy "Authenticated Upload" on storage.objects for insert with check ( bucket_id = 'leave_docs' and auth.role() = 'authenticated' );

-- Seed Data
-- Note: UUIDs here are placeholders. In reality, you'd Create Auth User -> Get UUID -> Insert here.
-- For the purpose of this script, we assume these users will be created in Auth with these exact UUIDs or we manually insert.
-- Ideally, use a function or just instructions.

-- Instructions:
-- 1. Sign up 'warden@sec.edu' manually in Supabase Auth.
-- 2. Sign up 'student1@sec.edu' manually.
-- 3. Sign up 'student2@sec.edu' manually.
-- 4. Run the following updates replacing the UUIDs with the actual ones from `auth.users`.

/*
INSERT INTO public.users (id, register_number, full_name, role, hostel_block, room_number, parent_mobile)
VALUES 
    ('REPLACE_WITH_WARDEN_UUID', 'W001', 'Chief Warden', 'warden', 'Admin Block', '101', '9999999999'),
    ('REPLACE_WITH_STUDENT1_UUID', 'S101', 'John Doe', 'student', 'Block A', '101', '9876543210'),
    ('REPLACE_WITH_STUDENT2_UUID', 'S102', 'Jane Smith', 'student', 'Block B', '202', '9123456780');
*/
